<!-- City -->
        <div class="animate-fade-up delay-4 flex flex-col gap-1 w-full">
          <label class="text-xs font-medium text-gray-500 pl-1">Ville</label>
          <select name="ville" class="w-full px-4 py-3 rounded-xl border border-gray-200 bg-gray-50 text-sm text-gray-900 outline-none focus:border-gray-900 focus:bg-white focus:ring-2 focus:ring-gray-900/5 transition-all">
            <option value="" disabled selected>Sélectionner une ville</option>
            <option value="Casablanca">Casablanca</option>
            <option value="Rabat">Rabat</option>
            <option value="Marrakech">Marrakech</option>
            <option value="Fes">Fès</option>
            <option value="Tanger">Tanger</option>
            <option value="Agadir">Agadir</option>
            <option value="Meknes">Meknès</option>
            <option value="Oujda">Oujda</option>
            <option value="Kenitra">Kénitra</option>
            <option value="Tetouan">Tétouan</option>
            <option value="Sale">Salé</option>
            <option value="Temara">Temara</option>
            <option value="Safi">Safi</option>
            <option value="El youssufia">El youssufia</option>
            <option value="El Jadida">El Jadida</option>
            <option value="Beni Mellal">Béni Mellal</option>
            <option value="Nador">Nador</option>
            <option value="Mohammedia">Mohammédia</option>
            <option value="Khouribga">Khouribga</option>
            <option value="Settat">Settat</option>
            <option value="Berrechid">Berrechid</option>
            <option value="Khemisset">Khémisset</option>
            <option value="Taza">Taza</option>
            <option value="Inezgane">Inezgane</option>
            <option value="Larache">Larache</option>
            <option value="Ksar El Kebir">Ksar El Kébir</option>
            <option value="Guelmim">Guelmim</option>
            <option value="Berkane">Berkane</option>
            <option value="Al Hoceima">Al Hoceima</option>
            <option value="Taourirt">Taourirt</option>
            <option value="Ouarzazate">Ouarzazate</option>
            <option value="Tiznit">Tiznit</option>
            <option value="Errachidia">Errachidia</option>
            <option value="Azrou">Azrou</option>
            <option value="Ifrane">Ifrane</option>
            <option value="Bouskoura">Bouskoura</option>
            <option value="Dakhla">Dakhla</option>
            <option value="Laayoune">Laâyoune</option>
            <option value="Tan-Tan">Tan-Tan</option>
            <option value="Sidi Ifni">Sidi Ifni</option>
            <option value="Zagora">Zagora</option>
            <option value="Midelt">Midelt</option>
            <option value="Sidi Slimane">Sidi Slimane</option>
            <option value="Chefchaouen">Chefchaouen</option>
            <option value="Ouezzane">Ouezzane</option>
          </select>
        </div><?php /**PATH C:\laragon\www\N-A-S\resources\views/components/Forms/villes.blade.php ENDPATH**/ ?>